In [1]:
import numpy as np

Create a 1D NumPy array with integers from 1 to 20

In [2]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Calculate the sum, mean, median, and standard deviation of the elements in the array.  


In [3]:
sum_arr = np.sum(arr)
print(sum_arr)

210


In [4]:
mean_arr = np.mean(arr)
print(mean_arr)

10.5


In [5]:
median_arr = np.median(arr)
print(median_arr)

10.5


In [6]:
std_dev = np.std(arr)
print(std_dev)

5.766281297335398


Find the indices of elements greater than 10 in the array.

In [7]:
indices = np.where(arr > 10)
print(indices)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  

In [8]:
arr2 = np.arange(1,17).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Find the transpose of the array. 

In [9]:
transpose_arr = np.transpose(arr2)
print(transpose_arr)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


Calculate the row-wise and column-wise sums of the array. 

In [10]:
row_sum = np.sum(arr2,axis=0)
print(row_sum)

[28 32 36 40]


In [11]:
col_sum = np.sum(arr2,axis=1)
print(col_sum)

[10 26 42 58]


Create two 3 X 3 arrays filled with random integers between 1 and 20.

In [12]:
arr3_1 = np.random.randint(1, 21, size=(3, 3))
print (arr3_1)

[[ 1 18 11]
 [ 3  9  6]
 [15 11 18]]


In [13]:
arr3_2 = np.random.randint(1, 21, size=(3, 3))
print (arr3_2)

[[ 2 16 17]
 [ 1 10  1]
 [11  8 14]]


Perform element-wise addition, subtraction, and multiplication. 

In [14]:
addition = arr3_1 + arr3_2
print (addition)

[[ 3 34 28]
 [ 4 19  7]
 [26 19 32]]


In [15]:
substraction = arr3_1 - arr3_2
print (substraction)

[[-1  2 -6]
 [ 2 -1  5]
 [ 4  3  4]]


In [16]:
multiplication = arr3_1 * arr3_2
print (multiplication)

[[  2 288 187]
 [  3  90   6]
 [165  88 252]]


Compute the dot product of the two arrays.

In [17]:
dot_product = np.dot(arr3_1,arr3_2)
print(dot_product)

[[141 284 189]
 [ 81 186 144]
 [239 494 518]]


Reshape a 1D array of size 12 into a 3 X 4 2D array

In [18]:
arr1 = np.arange(1,13)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
arr1_2 = arr1.reshape(3,4)
print(arr1_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


slice the first two rows and last two columns.  

In [20]:
sliced_arr = arr1_2[:2, -2:]
print(sliced_arr)

[[3 4]
 [7 8]]
